version: "3.8"
services:
  web:
    image: nginx:1.19.2
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./code:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
    restart: always

  php:
    build: ./php-with-ext
    ports:
      - "8000:8000"
    volumes:
      - ./code:/var/www/html
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always

  nodejs:
    image: node:14.11.0-stretch
    volumes:
      - ./code:/var/www/html
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: always